### ISSUE TITLE
secrets inside .travis.yml

### ISSUE THREAD

**Issue by RobertDober** [locomotivecms/steam#189]
Related to https://github.com/locomotivecms/wagon/issues/392

```yaml
env:
  - CODECLIMATE_REPO_TOKEN=************************************************************
addons:
  code_climate:
    repo_token: *******************************************************************
```
