### ISSUE TITLE
rc6: memory adapter: comparison of Array with Array failed

### ISSUE THREAD

**Issue by rvalyi** [locomotivecms/steam#44]
stack trace:

```
Arrrghhhh, we could not render page

comparison of Array with Array failed

File: ?

Code

No code

Back trace

/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/adapters/memory/query.rb:74:in `sort_by'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/adapters/memory/query.rb:74:in `sorted'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/adapters/memory/query.rb:68:in `all'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/repositories/content_entry_repository.rb:47:in `all'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/liquid/drops/content_entry_collection.rb:59:in `collection'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/liquid/drops/content_entry_collection.rb:8:in `each'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/utils.rb:23:in `slice_collection_using_each'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/utils.rb:8:in `slice_collection'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/for.rb:88:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:71:in `block in render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/context.rb:128:in `stack'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/tags/inherited_block.rb:64:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/liquid/tags/inherited_block.rb:42:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block.rb:15:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:105:in `render_token'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:87:in `block in render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `each'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/block_body.rb:74:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:215:in `block in render'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:269:in `with_profiling'
/var/lib/gems/2.2.0/gems/locomotivecms-liquid-4.0.0/lib/liquid/template.rb:214:in `render'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/renderer.rb:34:in `parse_and_render_liquid'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/renderer.rb:22:in `render_page'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/renderer.rb:10:in `_call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/path.rb:13:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/locale.rb:24:in `block in _call'
/var/lib/gems/2.2.0/gems/i18n-0.7.0/lib/i18n.rb:257:in `with_locale'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/locale.rb:23:in `_call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/timezone.rb:16:in `block in _call'
/var/lib/gems/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/timezone.rb:15:in `_call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/robots.rb:15:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/logging.rb:18:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:18:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/default_env.rb:15:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:23:in `next'
/var/lib/gems/2.2.0/gems/locomotivecms_wagon-2.0.0.rc2/lib/locomotive/wagon/middlewares/error_page.rb:16:in `_call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/thread_safe.rb:13:in `call'
/var/lib/gems/2.2.0/gems/dragonfly-1.0.12/lib/dragonfly/middleware.rb:14:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/dynamic_assets.rb:20:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/static.rb:124:in `call'
/var/lib/gems/2.2.0/gems/locomotivecms_steam-1.0.0.rc6/lib/locomotive/steam/middlewares/favicon.rb:15:in `call'
/var/lib/gems/2.2.0/gems/rack-rewrite-1.5.1/lib/rack/rewrite.rb:24:in `call'
/var/lib/gems/2.2.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:86:in `block in pre_process'
/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `catch'
/var/lib/gems/2.2.0/gems/thin-1.6.4/lib/thin/connection.rb:84:in `pre_process'
/var/lib/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `call'
/var/lib/gems/2.2.0/gems/eventmachine-1.0.8/lib/eventmachine.rb:1062:in `block in spawn_threadpool'
```

template:
```
{% block 'body' %}
%section#about.white-bg.padding-top
  .container.features
    %p.section-description {% editable_text "opensourceDescription" %} null {% endeditable_text %}
    .row
      .col-sm-8
        {% for project in contents.open_source %}
        .col-sm-4.scrollimation.fade-up
          .media
            .icon.pull-left
              %img{:alt => "", :src => "{{ project.image.url }}", :width => "50px"}/
            .media-body
              %h4 {{ project.title }}
              %p {{ project.description_short }}
              %a{:href => "{{ project.project_link }}", :target => "_blank"}
        {% endfor %}

{% endblock %}
```

ugly work around: change the sorted method in query.rb to:
```
        def sorted(entries)
          return entries if @sorting.blank?

          begin
            entries.sort_by { |entry| @sorting.apply_to(entry, @locale) }
          rescue
            entries
          end
        end
```

Hope this helps

**Comment by did** [comment]
@rvalyi thanks for the bug report. Unfortunately, I need more information like the content type definition, if there is or not a with_scope wrapping your code.
thanks!

**Comment by rvalyi** [comment]
Hello @did 
no with_scope wrapping in this template.

The content type definition is:
```
---
name: Open Source
description: open source contributions
slug: open_source
label_field_name: title
order_by: sequence
order_direction: asc
fields:
- title:
    label: title
    type: string
    required: true
    unique: false
    localized: true
- description_short:
    label: description_short
    type: text
    required: true
    unique: false
    localized: true
    text_formatting: html
- description:
    label: description
    type: text
    required: false
    unique: false
    localized: true
    text_formatting: html
- description_markdown:
    label: description_markdown
    type: text
    required: false
    unique: false
    localized: true
    text_formatting: none
- project_link:
    label: project_link
    type: string
    required: false
    unique: false
    localized: false
- documentation_link:
    label: documentation_link
    type: string
    required: false
    unique: false
    localized: false
- image:
    label: image
    type: file
    required: true
    unique: false
    localized: false
- sequence:
    label: sequence
    type: string
    required: true
    unique: false
    localized: true
- size:
    label: size
    type: select
    required: true
    unique: false
    localized: true
    select_options:
      en:
      - normal
      - big
      - very big
      - - en
      - - fr
      - - pt-BR
      fr:
      - normal
      - big
      - very big
      - 
      - 
      - 
      pt-BR:
      - normal
      - big
      - very big
      - 
      - 
      - 
- published:
    label: published
    type: boolean
    required: false
    unique: false
    localized: false
```

I now see we have these empty -. Not sure how it comes from, probably some export from our older locomotive v2. I have no idea if these empty slots have something to do with this error.
