### ISSUE TITLE
translation & pluralization

### ISSUE THREAD

**Issue by adam-pl** [locomotivecms/steam#50]
Let's say we have defined some translation in file `config/translations.yml`:

    found:
      one: "Found one result"
      other: "Found %{count} results"

Now we want to use it. In Ruby we could do in this way:

    I18n.translate :found, :count => result_count

How to do that with Liquid?
Should I create new Filter?

**Comment by did** [comment]
@adam-pl we need to improve the existing translation service (https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/services/translator_service.rb) used by the translate filter (https://github.com/locomotivecms/steam/blob/master/lib/locomotive/steam/liquid/filters/translate.rb)

**Comment by did** [comment]
we've got 3 cases: none, one and other, right?

**Comment by adam-pl** [comment]
It depends on language, see http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html.
For example Welsh has 6 items: 
 - zero
 - one
 - two
 - few
 - many
 - other.

It might be interesting [Create Pluralised Translations](https://github.com/Locale/localeapp/wiki/Create-Pluralised-Translations) uses plural rule definitions from the [Unicode Common Locale Data Repository (CLDR)](http://unicode.org/repos/cldr-tmp/trunk/diff/supplemental/language_plural_rules.html).

**Comment by did** [comment]
@adam-pl, I implemented the behavior described in the Shopify documentation (https://docs.shopify.com/themes/theme-development/translations/translation-filter). 

There is one slight difference. For instance, if you want to translate the number of posts

````liquid
{{ post_count | translate: count: author.posts.count }}
````

you'll need to write the following syntax:

````yaml
post_count_zero:
  en: no post
  fr: aucun article
post_count_one:
  en: one post
  fr: un article
post_count_two:
  en: two posts
  fr: 2 articles
post_count_other:
  en: {{ count }} posts
  fr: {{ count }} articles
````

This feature is already in the master branch. It will be available in the gems this week.
