### ISSUE TITLE
422 Unprocessable Entity when declaring fields as localized

### ISSUE THREAD

**Issue by jepetko** [locomotivecms/steam#58]
hi, today I experienced a very specific problem while implementing a contact form according to your guide https://locomotive-v3.readme.io/docs/create-a-contact-form. When I submitted the form I received the HTTP code 422 (Unprocessable Entity). This is very confusing because this code is normally returned when the csrf  token is not passed. Also the errors part of the response is confusing because it complains about empty fields:

Data type (enquiries):
```
name: Enquiries
slug: enquiries
description: A description of the content type for the editors
label_field_name: name
order_by: manually
public_submission_enabled: true
fields:

- name: # The lowercase, underscored name of the field
    label: Name # Human readable name of the field
    type: string
    required: true
    hint: Enquirer name
    localized: true

- message: # The lowercase, underscored name of the field
    label: Message # Human readable name of the field
    type: text
    required: false
    hint: Message
    localized: false
    # text_formatting: html # html (uses rich text editor), markdown or text (uses plain text editor)
```

Form configuration in the page:
```html
<form method="POST" action="{{contents.enquiries.api.create}}.json" class="pure-form pure-form-stacked">
  {% csrf_param %}
  <input type="hidden" name="content_type_slug" value="enquiries">
  <div class="form_errors">
    {{ 'enquiry_error_text' | translate }}
    <ul>
        <li></li>
    </ul>
  </div>
  <div class="form_notification">{{ 'enquiry_success_text' | translate }}</div>
  <fieldset>

      <label class="control-label" for="inputName">{{ 'enquirer_name' | translate }}</label>
      <input type="text" id="inputName" name="entry[name]" class="span4" required>

      <label class="control-label" for="inputComment">{{ 'enquirer_message' | translate}}</label>
      <textarea id="inputComment" rows="6" name="entry[message]" class="span4" required></textarea>

      <button type="submit" class="pure-button">{{ 'enquiry_submit' | translate }}</button>
  </fieldset>
</form>
```

Note: I'm using "entry[...]" for input fields names because I stumbled upon the RSpec tests which are using this keyword too. "content[...]" should work as well.

Response (```name can't be blank```):
```javascript
{
	"_id": null,
	"_slug": null,
	"_label": "John Doe",
	"_visible": true,
	"_position": 0,
	"content_type_slug": "enquiries",
	"created_at": "2016-01-31T21:27:29.033Z",
	"updated_at": "2016-01-31T21:27:29.033Z",
	"name": "John Doe",
	"message": "Hello.",
	"errors": {
		"name": ["can't be blank"]      //<<<<<<<---- BUT: name is not blank
	},
	"seo_title": null,
	"meta_description": null,
	"meta_keywords": null
}
```

The problem was that the field ```name``` was defined ```localized: true```. Setting it to ```false``` solved the issue.
